import catchErrorAsync from '../utils/catch-err-async.js';

export const getCheckoutSession = catchErrorAsync(async (req, res, next) => {
  // 1) find the tour with that id
});

export const getBookings = '';
